/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.apifirst.api;

import com.example.apifirst.model.SayHello200Response;
import com.example.apifirst.model.SayHelloRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-05-06T22:15:28.907398500-04:00[America/New_York]", comments = "Generator version: 7.13.0")
@Validated
@Tag(name = "hello", description = "the hello API")
public interface HelloApi {

    default HelloApiDelegate getDelegate() {
        return new HelloApiDelegate() {};
    }

    /**
     * POST /hello : Say hello to a person
     * Returns a greeting message for the provided name
     *
     * @param sayHelloRequest  (required)
     * @return Successful operation (status code 200)
     */
    @Operation(
        operationId = "sayHello",
        summary = "Say hello to a person",
        description = "Returns a greeting message for the provided name",
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SayHello200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/hello",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<SayHello200Response> sayHello(
        @Parameter(name = "SayHelloRequest", description = "", required = true) @Valid @RequestBody SayHelloRequest sayHelloRequest
    ) {
        return getDelegate().sayHello(sayHelloRequest);
    }

}
